name: publish

on:
  workflow_dispatch:
    inputs:
      deploy_version:
        description: 'The version to be deployed (tag name, ex: v1.0)'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set release version
        run: |
          sed -i 's/<<version>>/${{ github.event.inputs.deploy_version }}/g' ./k8s/deploy-prod.yml
      -
        name: Push to k8s
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.VINACIS_KUBE_CONFIG }}
          command: apply -f ./k8s/deploy-prod.yml
      
